### ISSUE TITLE
Mrdmd can not make predictions

### ISSUE THREAD

**Issue by Paclim** [mathLab/PyDMD#114]
Hi, 
I am experiencing the following problem:
Mrdmd is able to reconstruct just the data used to fit the model but if we  manipulate the interval between the approximated states or extend the temporal window where the data is reconstructed (as shown in Tutorial 2) this does not have any effect on the shape of the reconstructed data.

example:
Mrdmd.reconstructed_data.shape= (1000,200)
Mrdmd.dmd_time['dt'] *=1
Mrdmd.dmd_time['tend'] += 100
Mrdmd.reconstructed_data.shape= (1000,200) 
where the last line should be:
 Mrdmd.reconstructed_data.shape= (1000,300) 

Thanks for your work,
Best regards

**Comment by ndem0** [comment]
See #63.

**Comment by camdus** [comment]
Hi @ndem0, 

I am working on mrDMD for my master Thesis at Université Libre de Bruxelles. I would like to know how you plan to make prediction possible through mrDMD? I'm asking because you said "we are working on it" and I'm curious to know how you see this happening. 

tank you for your reply! 

Camille
