### ISSUE TITLE
How do I use DMD for prediction\extrapolation?

### ISSUE THREAD

**Issue by ovgeorge** [mathLab/PyDMD#63]
I've tried exactly like in the tutorial 2 to learn on the beginning of time series to make prediction about the future:

```
T_LEARN = 1000

snapshots = data_vec[:,:T_LEARN]
dmd = MrDMD(svd_rank=50, max_level=3, max_cycles=3)
dmd.fit(X = np.complex128(snapshots))

tend = 3604

dmd.dmd_time['tend'] = tend

print(np.shape(dmd.reconstructed_data))
print(np.shape(dmd.dmd_timesteps))
print(np.shape(snapshots))
```

and I'm getting 
```
(28800, 1000)
(3605,)
(28800, 1000)
```
So, the size of dmd.dmd_timesteps is still of the initial time series I've used for learning.

So, I just have some kind of low-rank approximation to beginning of the time series I've used for learning, but not the extrapolation I've seen in this picture 

![index](https://user-images.githubusercontent.com/12253907/37628088-cff5bab8-2be8-11e8-8640-33286513a566.png)

My code is very similar to code from tutorial, although I don't understand why you needed to compute integral (and twice!). 

```
compute_integral = scipy.integrate.trapz

original_int = [compute_integral(compute_integral(snapshot)).real for snapshot in snapshots]
dmd_int = [compute_integral(compute_integral(state)).real for state in dmd_states]

figure = plt.figure(figsize=(18, 5))
plt.plot(dmd.original_timesteps, original_int, 'bo', label='original snapshots')
plt.plot(dmd.dmd_timesteps, dmd_int, 'r.', label='dmd states')
plt.ylabel('Integral')
plt.xlabel('Time')
plt.grid()
leg = plt.legend()
```

**Comment by ndem0** [comment]
The issue reagards the multi-resolution version you are trying to use: due to the recursive splits of the temporal domain, we are not able to deal with prediction for this variant at the moment. If you are interested on this version, we recommend the original work by Kutz [DOI](https://epubs.siam.org/doi/10.1137/15M1023543). Anyway, we are working on it! You can try with another version meantime.

About the other (minor) question you asked,  I computed twice the integral just because the scipy trapezium method implementation: the domain is 2D, so i need to apply the method once for each direction.

**Comment by camdus** [comment]
Hi @ndem0,

I am working on mrDMD for my master Thesis at Université Libre de Bruxelles. I would like to know how you plan to make prediction possible through mrDMD? I'm asking because you said "we are working on it" and I'm curious to know how you see this happening.

tank you for your reply!

Camille
